In [1]:
import numpy as np

#### MSE(Mean Squared Error)

$$
{MSE} = \frac{1}{n}{\sum (y_i - \hat{y_i} )^2}
$$

In [2]:
# y절편 a와 기울기 b.
y절편 = 76
기울기 = 3

In [3]:
# 입력과 결과.
입력 = [2, 4, 6, 8]
결과 = [81, 93, 91, 97]

In [4]:
# 입력된 값에 따라 결과를 예측하는 함수.
def predict(x) :
    return 기울기 * x + y절편

In [5]:
# 예측 결과를 추출.
# 예측 결과를 담을 리스트.
predList = []

for x in 입력 :
    pred = predict(x)
    predList.append(pred)
    
predList

[82, 88, 94, 100]

In [6]:
# 계산을 쉽게 하기 위해 ndarray를 생성.
array1 = np.array(predList)
array2 = np.array(결과)

print(array1)
print(array2)

[ 82  88  94 100]
[81 93 91 97]


In [7]:
# 진짜 결과와 예측 결과를 뺀 값을 가져옴.
array3 = array1 - array2
print(array3)

[ 1 -5  3  3]


In [8]:
# 제곱을 구함.
array4 = array3 ** 2
print(array4)

[ 1 25  9  9]


In [9]:
# 평균을 구함.
mse = array4.mean()
print(f'MSE : {mse}')

MSE : 11.0
